// <auto-generated />
using System;
using Hospital.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Db.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20260405132228_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Db.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderType")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceYears = 2,
                            FirstName = "Глеб",
                            GenderType = 1,
                            LastName = "Романенко",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExperienceYears = 3,
                            FirstName = "Семен",
                            GenderType = 1,
                            LastName = "Лобанов",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExperienceYears = 2,
                            FirstName = "Борис",
                            GenderType = 1,
                            LastName = "Левин",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExperienceYears = 1,
                            FirstName = "Варвара",
                            GenderType = 2,
                            LastName = "Черноус",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExperienceYears = 3,
                            FirstName = "Мария",
                            GenderType = 2,
                            LastName = "Колисниченко",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 6,
                            ExperienceYears = 1,
                            FirstName = "Светлана",
                            GenderType = 2,
                            LastName = "Чернышова",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 7,
                            ExperienceYears = 5,
                            FirstName = "Вячеслав",
                            GenderType = 1,
                            LastName = "Селезнев",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 8,
                            ExperienceYears = 7,
                            FirstName = "Станислав",
                            GenderType = 1,
                            LastName = "Башницен",
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 9,
                            ExperienceYears = 3,
                            FirstName = "Васелиса",
                            GenderType = 2,
                            LastName = "Шмид",
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 10,
                            ExperienceYears = 4,
                            FirstName = "Дарья",
                            GenderType = 2,
                            LastName = "Зайченко",
                            SpecialtyId = 4
                        },
                        new
                        {
                            Id = 11,
                            ExperienceYears = 1,
                            FirstName = "Анатолий",
                            GenderType = 1,
                            LastName = "Войченко",
                            SpecialtyId = 4
                        },
                        new
                        {
                            Id = 12,
                            ExperienceYears = 5,
                            FirstName = "Евгений",
                            GenderType = 1,
                            LastName = "Шевчук",
                            SpecialtyId = 5
                        },
                        new
                        {
                            Id = 13,
                            ExperienceYears = 2,
                            FirstName = "Катерина",
                            GenderType = 2,
                            LastName = "Главко",
                            SpecialtyId = 5
                        },
                        new
                        {
                            Id = 14,
                            ExperienceYears = 3,
                            FirstName = "Елизавета",
                            GenderType = 2,
                            LastName = "Сидорчук",
                            SpecialtyId = 6
                        },
                        new
                        {
                            Id = 15,
                            ExperienceYears = 8,
                            FirstName = "Петр",
                            GenderType = 1,
                            LastName = "Иващенко",
                            SpecialtyId = 6
                        },
                        new
                        {
                            Id = 16,
                            ExperienceYears = 2,
                            FirstName = "Тарас",
                            GenderType = 1,
                            LastName = "Гайдар",
                            SpecialtyId = 7
                        },
                        new
                        {
                            Id = 17,
                            ExperienceYears = 5,
                            FirstName = "Анастасия",
                            GenderType = 2,
                            LastName = "Громова",
                            SpecialtyId = 7
                        },
                        new
                        {
                            Id = 18,
                            ExperienceYears = 4,
                            FirstName = "Вероника",
                            GenderType = 2,
                            LastName = "Борова",
                            SpecialtyId = 8
                        },
                        new
                        {
                            Id = 19,
                            ExperienceYears = 2,
                            FirstName = "Оксана",
                            GenderType = 2,
                            LastName = "Свиридова",
                            SpecialtyId = 9
                        },
                        new
                        {
                            Id = 20,
                            ExperienceYears = 3,
                            FirstName = "Полина",
                            GenderType = 2,
                            LastName = "Ушакова",
                            SpecialtyId = 9
                        },
                        new
                        {
                            Id = 21,
                            ExperienceYears = 6,
                            FirstName = "Денис",
                            GenderType = 1,
                            LastName = "Никифоров",
                            SpecialtyId = 9
                        });
                });

            modelBuilder.Entity("Hospital.Db.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderType")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Hospital.Db.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Терапия",
                            Price = 40m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кардиология",
                            Price = 80m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Неврология",
                            Price = 75m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Офтальмология",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ортопедия",
                            Price = 70m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Эндокринология",
                            Price = 65m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Пульмонология",
                            Price = 70m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Психиатрия",
                            Price = 90m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Стоматология",
                            Price = 85m
                        });
                });

            modelBuilder.Entity("Hospital.Db.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hospital.Db.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital.Db.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Db.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Hospital.Db.Entities.Doctor", "UserId");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Db.Entities.Patient", b =>
                {
                    b.HasOne("Hospital.Db.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Hospital.Db.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Db.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
